"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

type Lesson={id:string;slug:string;title:string;summary:string;content:string;points:string[];quiz_question:string;quiz_options:string[];quiz_answer:number;position:number;published:boolean};
type Course={id:string;slug:string;title:string;description:string;level:string;duration:string;published:boolean;lessons:Lesson[]};

export default function CourseEditor({params}:{params:Promise<{slug:string}>}) {
  const [slug,setSlug]=useState(""); const [course,setCourse]=useState<Course|null>(null); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  useEffect(()=>{params.then(p=>{setSlug(p.slug); fetch("/api/admin/courses").then(async r=>{const d=await r.json(); if(!r.ok) throw new Error(d.error); const found=d.courses.find((x:Course)=>x.slug===p.slug); if(!found) throw new Error("Course not found"); setCourse(found);}).catch(e=>setError(e.message));});},[params]);
  if(error) return <main className="min-h-screen bg-[#f8fafc] p-8"><p className="mx-auto max-w-3xl rounded-xl bg-red-50 p-5 text-red-700">{error}</p></main>;
  if(!course) return <main className="min-h-screen bg-[#f8fafc] p-8 text-slate-500">Loading editor…</main>;
  const currentCourse = course;
  async function saveCourse(){setSaving(true);setError("");const r=await fetch("/api/admin/courses/"+currentCourse.slug,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:currentCourse.title,description:currentCourse.description,level:currentCourse.level,duration:currentCourse.duration,published:currentCourse.published})});if(!r.ok){const d=await r.json();setError(d.error||"Save failed");}setSaving(false);}
  async function saveLesson(l:Lesson){const r=await fetch("/api/admin/lessons/"+l.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(l)});if(!r.ok){const d=await r.json();setError(d.error||"Lesson save failed");return false;}return true;}
  async function toggleLesson(l:Lesson){const ok=await saveLesson({...l,published:!l.published});if(ok)setCourse({...currentCourse,lessons:currentCourse.lessons.map(x=>x.id===l.id?{...x,published:!x.published}:x)});}
  async function move(l:Lesson,direction:-1|1){const sorted=[...currentCourse.lessons].sort((a,b)=>a.position-b.position);const i=sorted.findIndex(x=>x.id===l.id),j=i+direction;if(j<0||j>=sorted.length)return;const a=sorted[i],b=sorted[j];const ok1=await saveLesson({...a,position:b.position}),ok2=ok1&&await saveLesson({...b,position:a.position});if(ok2)setCourse({...currentCourse,lessons:sorted.map(x=>x.id===a.id?{...x,position:b.position}:x.id===b.id?{...x,position:a.position}:x)});}
  async function remove(l:Lesson){if(!confirm("Delete this lesson permanently?"))return;const r=await fetch("/api/admin/lessons/"+l.id,{method:"DELETE"});if(!r.ok){const d=await r.json();setError(d.error||"Delete failed");return;}setCourse({...currentCourse,lessons:currentCourse.lessons.filter(x=>x.id!==l.id)});}
  return <main className="min-h-screen bg-[#f8fafc]"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><Link href="/admin/courses" className="font-black text-[#0b1f3a]">← Course management</Link><span className="text-sm font-bold text-slate-500">Course Editor</span></div></header>
  <section className="mx-auto max-w-6xl px-6 py-10"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[#155eef]">Live CMS</p><h1 className="mt-2 text-4xl font-black text-[#0b1f3a]">{currentCourse.title}</h1><p className="mt-2 text-slate-500">Edit course information, lessons, publishing and order.</p></div><button onClick={saveCourse} disabled={saving} className="rounded-xl bg-[#0b1f3a] px-5 py-3 font-bold text-white disabled:opacity-50">{saving?"Saving…":"Save course"}</button></div>
  {error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}
  <div className="mt-8 rounded-2xl border border-slate-200 bg-white p-6"><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-bold text-slate-600">Title<input value={currentCourse.title} onChange={e=>setCourse({...currentCourse,title:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"/></label><label className="text-sm font-bold text-slate-600">Level<input value={currentCourse.level} onChange={e=>setCourse({...currentCourse,level:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"/></label><label className="text-sm font-bold text-slate-600">Duration<input value={currentCourse.duration} onChange={e=>setCourse({...currentCourse,duration:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"/></label><label className="flex items-center gap-3 text-sm font-bold text-slate-600 md:mt-7"><input type="checkbox" checked={currentCourse.published} onChange={e=>setCourse({...currentCourse,published:e.target.checked})}/> Published to students</label></div><label className="mt-5 block text-sm font-bold text-slate-600">Description<textarea value={currentCourse.description} onChange={e=>setCourse({...currentCourse,description:e.target.value})} className="mt-2 min-h-28 w-full rounded-xl border border-slate-200 px-4 py-3"/></label></div>
  <div className="mt-8 space-y-5">{[...currentCourse.lessons].sort((a,b)=>a.position-b.position).map((lesson,index)=><LessonEditor key={lesson.id} lesson={lesson} index={index} total={currentCourse.lessons.length} onSave={async l=>{const ok=await saveLesson(l);if(ok)setCourse({...currentCourse,lessons:currentCourse.lessons.map(x=>x.id===l.id?l:x)});}} onToggle={()=>toggleLesson(lesson)} onMove={d=>move(lesson,d)} onDelete={()=>remove(lesson)}/>)}</div></section></main>;
}

function LessonEditor({lesson,index,total,onSave,onToggle,onMove,onDelete}:{lesson:Lesson;index:number;total:number;onSave:(l:Lesson)=>Promise<void>;onToggle:()=>void;onMove:(d:-1|1)=>void;onDelete:()=>void}){
 const [draft,setDraft]=useState(lesson); const [saving,setSaving]=useState(false);
 useEffect(()=>setDraft(lesson),[lesson]);
 async function save(){setSaving(true);await onSave(draft);setSaving(false);}
 return <article className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="text-xs font-extrabold uppercase tracking-widest text-slate-400">Lesson {index+1}</span><h2 className="mt-1 text-xl font-black text-[#0b1f3a]">{lesson.title}</h2></div><div className="flex flex-wrap gap-2"><button onClick={()=>onMove(-1)} disabled={index===0} className="rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-30">↑</button><button onClick={()=>onMove(1)} disabled={index===total-1} className="rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-30">↓</button><button onClick={onToggle} className="rounded-lg border px-3 py-2 text-xs font-bold">{lesson.published?"Unpublish":"Publish"}</button><button onClick={onDelete} className="rounded-lg border border-red-100 px-3 py-2 text-xs font-bold text-red-600">Delete</button></div></div>
 <div className="mt-5 grid gap-5 md:grid-cols-2"><label className="text-sm font-bold text-slate-600">Title<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-bold text-slate-600">Slug<input value={draft.slug} onChange={e=>setDraft({...draft,slug:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-bold text-slate-600 md:col-span-2">Summary<textarea value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})} className="mt-2 min-h-24 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-bold text-slate-600 md:col-span-2">Lesson content<textarea value={draft.content} onChange={e=>setDraft({...draft,content:e.target.value})} placeholder="Write the full lesson here. Separate paragraphs with blank lines." className="mt-2 min-h-48 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-bold text-slate-600">Key concepts<textarea value={draft.points.join("\n")} onChange={e=>setDraft({...draft,points:e.target.value.split("\n")})} className="mt-2 min-h-28 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-bold text-slate-600">Quiz options<textarea value={draft.quiz_options.join("\n")} onChange={e=>setDraft({...draft,quiz_options:e.target.value.split("\n")})} className="mt-2 min-h-28 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-bold text-slate-600 md:col-span-2">Quiz question<input value={draft.quiz_question} onChange={e=>setDraft({...draft,quiz_question:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-bold text-slate-600">Correct option index<input type="number" min="0" value={draft.quiz_answer} onChange={e=>setDraft({...draft,quiz_answer:Number(e.target.value)})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><div className="flex items-end"><button onClick={save} disabled={saving} className="rounded-xl bg-[#155eef] px-5 py-3 font-bold text-white disabled:opacity-50">{saving?"Saving…":"Save lesson"}</button></div></div></article>;
}
